### ISSUE TITLE
Game unexpectedly wins early

### ISSUE THREAD

**Issue by 0x106** [danaugrs/royal-ur#1]
In some games it will declare a winner and exit when either player gets their first piece of the board. Not sure if this is a bug or a feature.

This only occured after I'd played a game, and then was playing consecutive games. I only played against the computer, on the 'standard' board layout. If I refreshed and played again then it would work as normal.

(And as an aside, this is a great game. I'm hooked already and love your implementation).

**Comment by danaugrs** [comment]
I'm glad you like it! That's a bug, thanks for reporting it - I'll investigate 😄

**Comment by danaugrs** [comment]
I've fixed it and updated the Android and WebGL builds accordingly.
Let me know if you find any other bugs!
