### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by sabinomaggi** [danaugrs/royal-ur#2]
> You could also keep tabs of the dice outcomes separately for the AI and for yourself and compare the probabilities.

Thanks for the tip, it could be a nice try. How can I keep separate tabs of dice outcomes in the online version of the game?

**Comment by danaugrs** [comment]
Hey - so by "keep tabs" I mean count the outcomes of the dice rolls separately for the AI and for yourself, using e.g. pen and paper or a [spreadsheet](http://spreadsheets.google.com). To do that you start a new game with the AI and play e.g. 100 moves (50 moves each). Then you count how many of each dice outcome you get over the entire game - how many 0s you got, how many 1s, how many 2s, how many 3s and how many 4s. Meanwhile, do the same for the AI - count how many of each dice outcome it gets. Once you have all the counts, divide each by 50 (the number of moves each player took) to obtain the empirical probabilities. Then you can compare the empirical probability distribution for the AI versus the one for yourself. They should approximately match each other. They should also both approximately match the true probabilities below:

<p align="center">
<img src="https://user-images.githubusercontent.com/5261448/54034416-8b07fd80-4195-11e9-8899-b6926629c4a5.png">
</p>

The more dice outcomes you count, the closer the empirical probabilities get to the real ones, and in the limit they should reach the real ones exactly. This is known as the [Central Limit Theory](https://en.wikipedia.org/wiki/Central_limit_theorem) in probability theory.

Thanks for the interest in the game! 😄 How did you find out about it?

**Comment by sabinomaggi** [comment]
So back to good old manual data acquisition! Il'll do that, you can bet it, the real problem is to have time to make a decent number of trials to check the null hypothesis (i.e., that dice probs are not affected by the random number generator).
As for the game, last summer I found this game on the Apple Store and I started enyoing it. Unfortunately, the iOS app I tried was limited, in that it only had one set of rules, and I started to look around for alternatives. Your implementation is the best I have found so far, except for this stange feeling about the unbalanced dice rolls.
